### ISSUE TITLE
Comments on solutions to Mastering Shiny

### ISSUE THREAD

**Issue by mpaulacaldas** [MayaGans/BayesianBabe#10]
Hi! Following up on your post to the R-Ladies slack channel, I thought I would leave you below some comments on your solutions given that I have also been working my way through the book. You are also more than welcome to have a look at mine and give me feedback! They are at <https://mastering-shiny-mpc-solutions.netlify.com/> (see right below the exercises for each chapter).

And bravo on your website 👏 It looks really nice!

## My comments

- In the [last exercise in chapter 2](https://maya.rbind.io/masteringshiny/example/chapter2/#2-8-5) the app doesn't work because calls to `plot()` take too long to render with data sets with many columns. You can replace `datasets <- "seals"` to see if everything was running OK.
- [I also](https://mastering-shiny-mpc-solutions.netlify.com/basic-ui.html#exercises-2) couldn't solve [3.3.5.2](https://maya.rbind.io/masteringshiny/example/chapter3/#3-3-5-2). If you have any thoughts I'd be happy to hear them!
- Minor style comment: In [5.8.3](https://maya.rbind.io/masteringshiny/example/chapter5/#5-8-3), I wouldn't name the reactive `n` since it would mask `dplyr::n()`. It's not an issue for this app but good to be aware of for apps that rely on a lot of dplyr code.
- In [8.1.5.1](https://maya.rbind.io/masteringshiny/example/chapter8/#8-1-5-1), `req()` internally checks if a value is truthy (source below), so you can write `req(input$year)` instead of `req(isTruthy(input$year))`. There are times where you may want to call `isTruthy()` instead of `req()`, but this is mostly when you want to write `if` conditions that depend on the `TRUE`/`FALSE` value returned by `isTruthy()`.
  
  ```r
  > shiny::req
  function (..., cancelOutput = FALSE) 
  {
      dotloop(function(item) {
          if (!isTruthy(item)) {
              if (isTRUE(cancelOutput)) {
                  cancelOutput()
              }
              else {
                  reactiveStop(class = "validation")
              }
          }
      }, ...)
      if (!missing(..1)) 
          ..1
      else invisible()
  }
  <bytecode: 0x7ff4c9ad1120>
  <environment: namespace:shiny>
  ```

- In [8.4.3.2](https://maya.rbind.io/masteringshiny/example/chapter8/#8-4-3-2) you wonder what `reduce()` does.  Here is a small example:
  ```r
  conditions <- list(TRUE, TRUE, TRUE, FALSE)
  conditions
  #> [[1]]
  #> [1] TRUE
  #> 
  #> [[2]]
  #> [1] TRUE
  #> 
  #> [[3]]
  #> [1] TRUE
  #> 
  #> [[4]]
  #> [1] FALSE
  
  purrr::reduce(conditions, `&`)
  #> [1] FALSE
  
  # is equivalent to...
  ((conditions[[1]] & conditions[[2]]) & conditions[[3]]) & conditions[[4]]
  #> [1] FALSE
  
  # or in "pipe" terms
  library(magrittr, warn.conflicts = FALSE)
  
  conditions[[1]] %>% 
    `&`(conditions[[2]]) %>% 
    `&`(conditions[[3]]) %>% 
    `&`(conditions[[4]])
  #> [1] FALSE
  ```
  <sup>Created on 2020-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MayaGans** [comment]
Addressed in PR d8f0cf29cfde0d5b22f2d1e519f62b8b5c9cb799 - thank you so much for the helpful comments! I also played with `reduce(conditions, `|`)` to really solidify your reprex and it finally clicked! 🙏
